---
apiVersion: v1
kind: Service
metadata:
  name: app-cpu
spec:
  selector:
    app: app-cpu
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-cpu
spec:
  selector:
    matchLabels:
      app: app-cpu
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: app-cpu
    spec:
      containers:
      - name: app-cpu
        image: ductn4/app-cpu:v1.0.0
        imagePullPolicy: Always
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80

